baseURL = "https://magamig.github.io/"
title = "Miguel Magalhães"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"
math= "true"

[params]
  description = ""
  copyright = ""
  dark = "off" #auto
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "map"
    name = "Map"
    title = "Map"
    url = "/map/"
    weight = 5
  
  [[menu.main]]
    identifier = "beers"
    name = "Beers"
    title = "Beers"
    url = "/beers/"
    weight = 10
  
  # [[menu.main]]
  #   identifier = "photos"
  #   name = "Photos"
  #   title = "Photos"
  #   url = "/photos/"
  #   weight = 15

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/posts/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
